apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: front
          image: front
          imagePullPolicy: "Never"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  ports:
    - nodePort: 31311
      port: 80
      protocol: TCP
  selector:
    app: frontend