apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: patient-front
spec:
  template:
    metadata:
      labels:
        app: patientfront
    spec:
      containers:
        - name: front
          image: front
          imagePullPolicy: "Never"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: patient-front
spec:
  type: NodePort
  ports:
    - nodePort: 31666
      port: 80
      protocol: TCP
  selector:
    app: patientfront